const LOCAL_STORAGE_ACCESS_KEY_KEY = "blankpage_key";

const TANSTACK_QUERY_STATUS_PENDING = "pending";
const TANSTACK_QUERY_STATUS_ERROR = "error";

const QUERY_KEY_ALL_BOOKS = "all_books";
const QUERY_KEY_SINGLE_BOOK = "single_book";

export {
    LOCAL_STORAGE_ACCESS_KEY_KEY,
    TANSTACK_QUERY_STATUS_PENDING,
    TANSTACK_QUERY_STATUS_ERROR,
    QUERY_KEY_ALL_BOOKS,
    QUERY_KEY_SINGLE_BOOK,
}
