// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package svcconfig

import (
	"fmt"
	"strings"
)

const (
	// StorageKindMemory is a StorageKind of type memory.
	StorageKindMemory StorageKind = "memory"
	// StorageKindPostgres is a StorageKind of type postgres.
	StorageKindPostgres StorageKind = "postgres"
)

var ErrInvalidStorageKind = fmt.Errorf("not a valid StorageKind, try [%s]", strings.Join(_StorageKindNames, ", "))

var _StorageKindNames = []string{
	string(StorageKindMemory),
	string(StorageKindPostgres),
}

// StorageKindNames returns a list of possible string values of StorageKind.
func StorageKindNames() []string {
	tmp := make([]string, len(_StorageKindNames))
	copy(tmp, _StorageKindNames)
	return tmp
}

// String implements the Stringer interface.
func (x StorageKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x StorageKind) IsValid() bool {
	_, err := ParseStorageKind(string(x))
	return err == nil
}

var _StorageKindValue = map[string]StorageKind{
	"memory":   StorageKindMemory,
	"postgres": StorageKindPostgres,
}

// ParseStorageKind attempts to convert a string to a StorageKind.
func ParseStorageKind(name string) (StorageKind, error) {
	if x, ok := _StorageKindValue[name]; ok {
		return x, nil
	}
	return StorageKind(""), fmt.Errorf("%s is %w", name, ErrInvalidStorageKind)
}

// MarshalText implements the text marshaller method.
func (x StorageKind) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *StorageKind) UnmarshalText(text []byte) error {
	tmp, err := ParseStorageKind(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *StorageKind) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

// Set implements the Golang flag.Value interface func.
func (x *StorageKind) Set(val string) error {
	v, err := ParseStorageKind(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *StorageKind) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *StorageKind) Type() string {
	return "StorageKind"
}
